"""mig

Revision ID: 43364db2942f
Revises: 9d09e1cb9b76
Create Date: 2024-12-04 23:06:03.475037

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '43364db2942f'
down_revision = '9d09e1cb9b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('phone_number', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    schema='my_app_schema'
    )
    op.create_table('discountcards',
    sa.Column('discount_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discount_percentage', sa.Numeric(), nullable=False),
    sa.Column('discount_conditions', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('discount_id'),
    schema='my_app_schema'
    )
    op.create_table('dishes',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('description', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('dish_id'),
    schema='my_app_schema'
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('position', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    schema='my_app_schema'
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('expiry_date', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    schema='my_app_schema'
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('contact_info', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id'),
    schema='my_app_schema'
    )
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['my_app_schema.suppliers.supplier_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id'),
    schema='my_app_schema'
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['my_app_schema.dishes.dish_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['my_app_schema.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id'),
    schema='my_app_schema'
    )
    op.create_table('tablereservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['my_app_schema.clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id'),
    schema='my_app_schema'
    )
    op.create_table('delivery_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['my_app_schema.deliveries.delivery_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['my_app_schema.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    schema='my_app_schema'
    )
    op.create_table('dishingredients',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['my_app_schema.products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['my_app_schema.recipes.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    schema='my_app_schema'
    )
    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('description', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['my_app_schema.dishes.dish_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['my_app_schema.recipes.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_id'),
    schema='my_app_schema'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_datetime', sa.Date(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['my_app_schema.clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['my_app_schema.discountcards.discount_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dish_id'], ['my_app_schema.dishes.dish_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['my_app_schema.employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['my_app_schema.products.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['my_app_schema.tablereservations.reservation_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id'),
    schema='my_app_schema'
    )
    op.drop_table('Clients', schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('client_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('client_id', name='Clients_pkey'),
    schema='my_app_schema'
    )
    op.drop_table('orders', schema='my_app_schema')
    op.drop_table('menu', schema='my_app_schema')
    op.drop_table('dishingredients', schema='my_app_schema')
    op.drop_table('delivery_items', schema='my_app_schema')
    op.drop_table('tablereservations', schema='my_app_schema')
    op.drop_table('recipes', schema='my_app_schema')
    op.drop_table('deliveries', schema='my_app_schema')
    op.drop_table('suppliers', schema='my_app_schema')
    op.drop_table('products', schema='my_app_schema')
    op.drop_table('employees', schema='my_app_schema')
    op.drop_table('dishes', schema='my_app_schema')
    op.drop_table('discountcards', schema='my_app_schema')
    op.drop_table('clients', schema='my_app_schema')
    # ### end Alembic commands ###
